apiVersion: v1
kind: Service
metadata:
  name: notification-management
  namespace: prakarsa
  labels:
    app: notification-management
spec:
  type: ClusterIP
  selector:
    app: notification-management
  ports:
    - name: http
      port: 80
      targetPort: 8080