apiVersion: v1
kind: Service
metadata:
  name: notification-management-api
  namespace: prakarsa
spec:
  type: ClusterIP
  selector: { app: notification-management-api }
  ports:
    - name: http
      port: 80
      targetPort: 8080
